# generated by datamodel-codegen:
#   filename:  watchdog.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, SecretStr


class ComponentKind(StrEnum):
    """
    Which Eugene Plexus component class a topology entry
    represents. Lives in `common.yaml` because more than one
    component references it: the watchdog's `/v1/components`, and
    (via `ConfigField.componentKindHint`) any component declaring
    a config field that points at a peer of a specific kind.

    A component is a **Eugene Plexus process**. Engine processes
    are not components and are not named here — they are runtimes,
    declared separately on the watchdog, because a third-party
    binary shares none of a component's declarative shape (no
    module, no config trio, no service token). See the watchdog's
    `GET /v1/runtimes`.

    `gateway` is the one OpenAI-compatible front door and there is
    exactly one. `inference-driver` instances are the per-backend
    wrappers and there are N — one per backend, wherever that
    backend lives.

    """

    gateway = 'gateway'
    inference_driver = 'inference-driver'


class Role(StrEnum):
    """
    The speaker of a single message in a conversation. Matches the
    OpenAI / Anthropic chat roles so adapters never re-shape on a hop.

    """

    system = 'system'
    user = 'user'
    assistant = 'assistant'


class Message(BaseModel):
    """
    A single message in a conversation. Deliberately close to the
    OpenAI / Anthropic chat message format so drivers don't have to
    re-shape on every hop.

    """

    role: Role
    content: str = Field(
        ...,
        description='Message text. Text-only for now; multimodal extensions deferred.',
    )
    timestamp: AwareDatetime | None = Field(
        None, description='When the message was produced. Server-assigned if omitted.'
    )


class BackendKind(StrEnum):
    """
    Which wire protocol an inference-driver instance speaks to its
    backend. Reported by the driver's `/v1/info` so the gateway can
    log it and the UI can render a label.

    `openai_compat_http` covers every local engine we care about
    (llama.cpp's `llama-server`, vLLM, LM Studio, Ollama) as well as
    hosted OpenAI-compatible services — the protocol is shared even
    though the providers are not, so `DriverInfo.provider` is what
    distinguishes them. `claude_code_cli` and `codex_cli` shell out
    to the respective CLIs, which is how a subscription the operator
    already pays for becomes just another backend.

    """

    anthropic_api = 'anthropic_api'
    openai_api = 'openai_api'
    claude_code_cli = 'claude_code_cli'
    codex_cli = 'codex_cli'
    openai_compat_http = 'openai_compat_http'


class Problem(BaseModel):
    """
    Error response shape, modeled on RFC 7807 (problem+json). Every
    Eugene Plexus component returns this for 4xx / 5xx responses.

    """

    type: str = Field(
        ...,
        description='A URI reference identifying the problem type, per RFC 7807.\nModeled as a plain string rather than `format: uri` to keep\nsentinel values like `about:blank` and ergonomic at call sites.\n',
    )
    title: str = Field(..., description='Short human-readable summary.')
    status: int = Field(..., description='HTTP status code.')
    detail: str | None = Field(
        None, description='Human-readable explanation specific to this occurrence.'
    )
    instance: str | None = Field(
        None,
        description='A URI reference identifying the specific occurrence. Modeled\nas a plain string for the same reason as `type`.\n',
    )
    component: str | None = Field(
        None,
        description='Eugene Plexus component name that originated the error\n(e.g. `"gateway"`, `"inference-driver:left"`).\n',
    )


class Status(StrEnum):
    ok = 'ok'
    degraded = 'degraded'
    error = 'error'


class Health(BaseModel):
    """
    Liveness / readiness response shape.
    """

    status: Status
    version: str | None = Field(None, description='Component version (semver).')
    component: str | None = Field(
        None, description='Component identifier (e.g. `"inference-driver"`).'
    )
    safeMode: bool | None = Field(
        False,
        description="True when the component was started with the watchdog's\nsafe-mode env var set\n(`EUGENE_PLEXUS_<KIND>_SAFE_MODE=1`) and is therefore\nrunning on built-in defaults instead of its persisted\nconfig. Components in safe mode are reachable for config\nediting (`PATCH /v1/config` writes to disk normally) but\nshould be considered non-functional for their primary\npurpose until restarted without the flag. `status` is\nalso reported as `degraded` while safe mode is in effect.\n",
    )
    details: dict[str, Any] | None = Field(
        None, description='Optional component-specific health detail.'
    )


class ConfigValueType(StrEnum):
    """
    The kind of value a config field holds. The UI uses this to pick
    a renderer (text input, dropdown, password field, etc.).

    """

    string = 'string'
    integer = 'integer'
    number = 'number'
    boolean = 'boolean'
    enum = 'enum'
    secret = 'secret'
    file_path = 'file_path'
    url = 'url'
    duration = 'duration'
    driver_list = 'driver_list'


class ConfigFieldShowWhen(BaseModel):
    """
    Predicate over another `ConfigField`'s current value. The UI
    renders the field this is attached to only when the named field
    equals the given value (or matches one entry in the given list).

    """

    key: str = Field(
        ...,
        description='`key` of another field in the same `ConfigSchema` to compare\nagainst.\n',
    )
    equals: Any = Field(
        ...,
        description="Value the named field must equal for this field to render.\nUntyped — when scalar, matches by literal equality against\nthe referenced field's `valueType`. When an array, matches\nif the referenced field's current value equals any entry\n(set-membership). Use the array form for a field that\napplies to multiple entries of an enum (e.g. an `apiKey`\nfield shared across several OpenAI-compatible providers).\n",
    )


class ConfigDocument(BaseModel):
    """
    Current effective config values, keyed by `ConfigField.key`.
    Values of fields with `sensitive: true` are returned as the
    literal string `"<redacted>"` regardless of whether they are
    set. Returned by `GET /v1/config`.

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigUpdateRequest(BaseModel):
    """
    Partial update for `PATCH /v1/config`. Every present key is
    set; absent keys are left unchanged. To revert a field to its
    default, send `null` as the value. Sensitive fields are written
    through directly (the redacted form sent back by GET is never
    accepted as a write value).

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigFieldError(BaseModel):
    """
    A per-field validation failure during PATCH.
    """

    key: str
    message: str


class ConfigUpdateResult(BaseModel):
    """
    Outcome of a `PATCH /v1/config` call. Validation failures on
    individual keys do not abort the whole request — valid changes
    are applied, invalid ones are reported in `rejected`.

    """

    applied: list[str] = Field(
        ..., description='Keys that were validated and applied successfully.'
    )
    rejected: list[ConfigFieldError] = Field(
        ...,
        description='Keys whose new values failed validation. The current value\nis preserved.\n',
    )
    requiresRestart: bool = Field(
        ...,
        description='True if any key in `applied` has `requiresRestart: true`,\nmeaning a process restart is needed for the change to take\neffect. The UI should surface this to the user.\n',
    )
    pendingRestart: list[str] | None = Field(
        None,
        description='Keys whose new values are stored but not yet active. Subset\nof `applied`. Empty unless `requiresRestart` is true.\n',
    )


class ConfigTestRequest(BaseModel):
    """
    Optional override for `POST /v1/config/test`. Same shape as
    `ConfigUpdateRequest`: keys override the saved config for the
    duration of the test only. Useful for "Test Connection" UIs where
    the operator wants to verify a new API key, URL, or model
    identifier before committing it. Send an empty body (`{}`) to
    test the saved config as-is.

    """

    overrides: ConfigUpdateRequest | None = None


class ConfigTestResult(BaseModel):
    """
    Result of a `POST /v1/config/test` invocation. Components decide
    what "test" means for their own surface: an inference-driver runs
    a minimal `generate()` round-trip against its backend; the
    gateway probes every driver it can route to; the library checks
    that its configured model directories are readable.

    """

    ok: bool = Field(
        ..., description='True iff the test invocation succeeded end-to-end.'
    )
    component: str = Field(
        ...,
        description='Component identifier (matches `ConfigSchema.component`).\nEchoed for UI clarity when several /v1/config/test responses\nland in the same view.\n',
    )
    latencyMs: int = Field(
        ..., description='Wall-clock time the test took, in milliseconds.'
    )
    summary: str | None = Field(
        None,
        description='One-line human-readable result summary. Always set when\n`ok` is true; may be set on failure to add context beyond\n`error`.\n',
    )
    sampleOutput: str | None = Field(
        None,
        description="Brief sample of the data the test produced — e.g. assistant\ntext from an inference-driver `generate()` round-trip. May be\ntruncated to keep the response small. Omitted when there's\nnothing useful to show.\n",
    )
    error: str | None = Field(
        None,
        description='Human-readable error message. Set when `ok` is false. Should\nbe specific enough that the operator can act on it (e.g.\n`"openaiApiKey rejected: 401 Unauthorized"`).\n',
    )


class SecurityMode(StrEnum):
    """
    Operator's choice for how the watchdog handles its master key
    between restarts. Set during the wizard's security screen; can
    be changed later from the Config page.

    * `prompt_on_startup` — passphrase required at every watchdog
      start. Master key lives only in process memory. Best for
      shared environments, sensitive conversations, security-
      conscious operators. A power outage means Eugene stays
      offline until the operator re-enters the passphrase.
    * `os_keyring` — master key stored in the OS secret store
      (Windows Credential Manager / macOS Keychain / Linux Secret
      Service via the `keyring` Python lib). OS unlocks tied to
      user login; Eugene auto-recovers from restarts. Best for
      home / personal-use installs and anyone who wants minimum
      friction. Anyone with the OS account can also start Eugene.

    """

    prompt_on_startup = 'prompt_on_startup'
    os_keyring = 'os_keyring'


class AuthLoginRequest(BaseModel):
    """
    Login request body sent by the UI to `POST /v1/auth/login` on
    the watchdog. The passphrase is the same one the operator set
    in the wizard. The watchdog bcrypt-compares it; on match,
    issues a session token.

    """

    passphrase: str = Field(..., min_length=1)


class AuthLoginResponse(BaseModel):
    """
    Issued on successful login. The UI stores `sessionToken` as a
    Secure / HttpOnly / SameSite=Strict cookie or in memory; every
    subsequent proxy request includes it as
    `Authorization: Bearer <token>`.

    """

    sessionToken: str = Field(
        ...,
        description='Opaque bearer token. Signed and validated server-side; the\nUI should never inspect its contents. Lifetime is bounded\nby `expiresAt`.\n',
    )
    expiresAt: AwareDatetime
    operatorName: str | None = Field(
        None,
        description='The operator\'s display name from the constitution\n(typically "operator" or whatever the operator set).\nEchoed for UI welcome strings.\n',
    )


class Alg(StrEnum):
    """
    Encryption algorithm identifier.
    """

    secretbox_xsalsa20poly1305 = 'secretbox-xsalsa20poly1305'


class MasterKeyEnvelope(BaseModel):
    """
    Encrypted-at-rest envelope for sensitive config fields. The
    on-disk YAML for fields marked `sensitive: true` is stored as
    this envelope when v0.2 security is enabled; the component
    decrypts using the master key passed in by the watchdog at
    spawn time (env var `EUGENE_PLEXUS_<KIND>_MASTER_KEY`,
    base64-encoded).

    Algorithm: libsodium secretbox (XSalsa20-Poly1305). The nonce
    is generated per-encryption and stored alongside the
    ciphertext. The master key is 32 bytes derived from the
    operator's passphrase via Argon2id with parameters chosen at
    first-run time and persisted in the watchdog's state.

    Components MAY accept plaintext values in PATCH requests
    (current behavior); on persist, they encrypt to this envelope
    if the master key is available. GET requests continue to
    return `"<redacted>"` for sensitive fields regardless of
    envelope-vs-plaintext on disk.

    """

    alg: Alg = Field(..., description='Encryption algorithm identifier.')
    nonce: str = Field(
        ...,
        description='Base64-encoded 24-byte nonce. Generated per-encryption,\nnever reused with the same key.\n',
    )
    ciphertext: str = Field(..., description='Base64-encoded ciphertext + auth tag.')


class RestartResult(BaseModel):
    """
    Acknowledgement returned by `POST /v1/admin/restart`. The
    component schedules its own process exit shortly after returning
    this response (typically a few hundred ms — long enough for the
    HTTP response to flush). The component does NOT bring itself
    back up; a process supervisor (systemd, docker-compose, the
    deploy launcher, etc.) is expected to relaunch it. In v0.1
    personal-use deploys without a supervisor, the operator
    relaunches manually.

    """

    scheduled: bool = Field(
        ...,
        description='True if the component accepted the restart and an exit is\nqueued. Always true in v0.1 — the endpoint has no reason to\nrefuse — but typed as a boolean so future versions can gate\non (e.g.) an in-flight long-running operation.\n',
    )
    delayMs: int = Field(
        ...,
        description='How long the component intends to wait before calling exit,\nmeasured from the moment the response is sent. Lets clients\ntime their UI ("restarting in 0.5s…") and decide when to\nstart polling `/healthz` for the relaunched process.\n',
        ge=0,
    )
    message: str | None = Field(
        None,
        description='Optional human-readable note (e.g. "logs flushed, exiting\nnow"). UI may display this in the restart-progress dialog.\n',
    )


class SpawnConfig(BaseModel):
    configFile: str = Field(
        ...,
        description="Absolute path to the component's own config file. The\nwatchdog passes this to the component via its\nkind-specific env var\n(`EUGENE_PLEXUS_<KIND>_CONFIG_FILE`) at spawn time.\n",
    )
    env: dict[str, str] | None = Field(
        None,
        description='Optional extra environment variables to pass to the\nspawned process. Reserved for advanced operators; the\nwizard never sets this.\n',
    )


class ComponentStatus(StrEnum):
    """
    Current operational state.

    * `starting` — watchdog has spawned the process but it has
      not yet answered `/healthz`.
    * `running` — process is up and `/healthz` is healthy.
    * `safe_mode` — process is up but launched with
      `SAFE_MODE=1`; will refuse to do useful work until the
      operator fixes its config and clears the safe-mode flag.
    * `exited` — process exited cleanly and the watchdog is in
      the middle of respawning it (transient state).
    * `crashed` — process has exited non-zero repeatedly and the
      watchdog has given up auto-restarting it. Operator must
      restart it manually after fixing the cause.
    * `unreachable` — for remote components, the watchdog can't
      reach the URL. For spawned components this state is not
      used (use `crashed` or `exited` instead).

    """

    starting = 'starting'
    running = 'running'
    safe_mode = 'safe_mode'
    exited = 'exited'
    crashed = 'crashed'
    unreachable = 'unreachable'


class EngineKind(StrEnum):
    """
    Which engine adapter constructs the argv and interprets
    readiness. Deliberately a closed enum rather than a free string:
    an engine is supported exactly when an adapter exists for it,
    and without an adapter there is nothing that knows how to start
    it or tell when it is ready.

    `llama_cpp` drives upstream `llama-server`. vLLM is a second
    adapter later, and MLX after that. We never ship an engine — all
    three are upstream projects we wrap and track.

    """

    llama_cpp = 'llama_cpp'


class AuthStatus(BaseModel):
    """
    Whether this install has been through first-run setup.

    """

    initialized: bool = Field(
        ...,
        description='True once a passphrase has been set. False means every\nendpoint except this one, `/healthz` and\n`POST /v1/auth/initialize` will refuse.\n',
    )


class AuthInitializeRequest(BaseModel):
    passphrase: SecretStr = Field(
        ...,
        description='The operator passphrase. Hashed with Argon2id and used to\nderive the master key that at-rest secrets are sealed\nunder, so losing it means losing every stored credential —\nthere is no recovery path by design.\n',
        min_length=1,
    )


class ManagedEngine(BaseModel):
    """
    A build this install fetched and owns, as opposed to one found on
    PATH or pointed at by hand. Present only when we installed it.

    """

    version: str = Field(
        ...,
        description='Upstream build identifier - for llama.cpp a `bNNNN` tag, not\na semver. Copied verbatim from the release, because the only\nuseful thing to do with it is compare it to what upstream\nhas.\n',
    )
    binaryPath: str = Field(
        ..., description='Absolute path to the executable inside the managed directory.'
    )
    variant: str = Field(
        ...,
        description='Which asset was chosen, e.g. `win-cuda-13.3-x64`. Recorded\nbecause it is the answer to "why is this slow" often enough\nto be worth surfacing: a host that fell back to a CPU build\nlooks identical from the outside otherwise.\n',
    )
    installedAt: AwareDatetime | None = None
    sizeBytes: int | None = Field(
        None,
        description='On-disk size of this build. A Windows CUDA install is roughly\nhalf a gigabyte unpacked and we retain two, so this is worth\nshowing before someone asks where their disk went.\n',
    )
    previousVersion: str | None = Field(
        None,
        description='The build retained alongside this one, if any. Retention is\ncurrent plus previous: keeping every build is not viable at\nthis size, and keeping only the newest leaves a bad upgrade\nwith no way back.\n',
    )


class Os(StrEnum):
    windows = 'windows'
    linux = 'linux'
    macos = 'macos'


class Arch(StrEnum):
    x64 = 'x64'
    arm64 = 'arm64'


class Accelerator(StrEnum):
    """
    `metal` is reported on Apple silicon even though there is no
    separate Metal asset - the plain macOS build has it compiled
    in, and saying `none` there would read as "no GPU".

    """

    none = 'none'
    cuda = 'cuda'
    rocm = 'rocm'
    metal = 'metal'
    sycl = 'sycl'


class HostAccelerator(BaseModel):
    """
    What the watchdog detected about this machine, insofar as it
    decides which engine build to fetch. Not a general hardware
    inventory - the VRAM-and-quant-fit surface that M3 needs belongs
    to the library component, not here.

    """

    os: Os | None = None
    arch: Arch | None = None
    accelerator: Accelerator | None = Field(
        None,
        description='`metal` is reported on Apple silicon even though there is no\nseparate Metal asset - the plain macOS build has it compiled\nin, and saying `none` there would read as "no GPU".\n',
    )
    acceleratorVersion: str | None = Field(
        None,
        description='For CUDA, the highest version the installed driver supports.\nSelection takes the highest published build whose major\nmatches and whose minor is no greater than this; a higher\nmajor is never chosen.\n',
    )


class EngineInstallRequest(BaseModel):
    version: str | None = Field(
        None,
        description='A specific upstream build to install. Omit for the newest.\nPresent so an operator who found a regression can pin the\nbuild that worked, which is the whole reason we record the\nversion rather than just "installed".\n',
    )


class State(StrEnum):
    """
    * `resolving` - asking upstream which build and which asset.
    * `downloading` - fetching. On Windows with CUDA this is two
      assets, the binary and a separate CUDA runtime, and the
      byte counters cover both.
    * `verifying` - comparing the SHA-256 the releases API
      reported for the asset. Upstream publishes no checksum
      file; the digest arrives with the asset metadata, so
      there is no excuse for skipping this.
    * `extracting` - unpacking into a new versioned directory.
    * `done` / `failed` / `cancelled` - terminal, and retained
      until the next install starts.

    """

    resolving = 'resolving'
    downloading = 'downloading'
    verifying = 'verifying'
    extracting = 'extracting'
    done = 'done'
    failed = 'failed'
    cancelled = 'cancelled'


class EngineInstall(BaseModel):
    """
    Progress of one install. Phases are named rather than reduced to
    a percentage because they fail differently and the operator
    needs to know which one they are in: a stall in `downloading` is
    the network, a stall in `extracting` is the disk, and a failure
    in `verifying` is the one that means do not run this.

    """

    engine: EngineKind
    state: State = Field(
        ...,
        description='* `resolving` - asking upstream which build and which asset.\n* `downloading` - fetching. On Windows with CUDA this is two\n  assets, the binary and a separate CUDA runtime, and the\n  byte counters cover both.\n* `verifying` - comparing the SHA-256 the releases API\n  reported for the asset. Upstream publishes no checksum\n  file; the digest arrives with the asset metadata, so\n  there is no excuse for skipping this.\n* `extracting` - unpacking into a new versioned directory.\n* `done` / `failed` / `cancelled` - terminal, and retained\n  until the next install starts.\n',
    )
    version: str | None = Field(
        None, description='The build being installed, once resolved.'
    )
    variant: str | None = None
    bytesDownloaded: int | None = None
    bytesTotal: int | None = Field(
        None,
        description='Total across every asset this install needs. Absent until\n`resolving` finishes.\n',
    )
    message: str | None = Field(
        None, description='What is happening now, for a status line.'
    )
    error: str | None = Field(None, description='Populated when `state: failed`.')
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None


class Origin(StrEnum):
    """
    Where the binary came from.

    * `managed` — fetched and verified by us. The one-click
      path; not implemented until engine acquisition lands.
    * `configured` — an explicit path the operator set, because
      they build llama.cpp themselves or want a specific build.
    * `path` — found on `PATH`.

    """

    managed = 'managed'
    configured = 'configured'
    path = 'path'


class RuntimeSpec(BaseModel):
    """
    Declarative half of a Runtime — what the operator asked for.
    Used for create and update bodies; observed fields are
    server-owned and excluded.

    Note what is *not* here: a command line. The operator declares
    intent (this engine, this model, these flags) and the adapter
    builds the argv. Letting a topology entry carry raw argv would
    make every engine "supported" while making none of them
    knowable — no readiness probe, no flag validation, no version
    story. The resolved argv is reported back on `Runtime.argv` for
    debugging, which is the half of raw-argv access that is
    genuinely useful.

    """

    name: str = Field(
        ...,
        description="Operator-supplied label, unique per install. Referenced by\nan inference-driver's config to say which runtime it fronts.\n",
        min_length=1,
    )
    engine: EngineKind
    modelPath: str = Field(
        ...,
        description="Absolute path to the model on this host — a `.gguf` file, or\na directory for multi-file formats. **The operator's own\npath, in the operator's own layout.** We never relocate,\nrename, or hash-address a model file; a runtime points at\nwhere the user put it.\n",
    )
    modelAlias: str | None = Field(
        None,
        description='The model id this runtime serves under, and therefore what a\nclient asks the gateway for. Defaults to the model\nfilename with its extension stripped — plainly-named files\nmean the obvious name is already the right one, so this is\nan override, not a requirement.\n',
    )
    host: str | None = Field(
        '127.0.0.1',
        description="Address the engine binds. Defaults to loopback: an engine\nhas no auth of its own, so it must not be exposed directly.\nReaching a model from another machine is the gateway's job,\nand the gateway has auth.\n",
    )
    port: int | None = Field(
        None,
        description='Port the engine binds. Assigned from an ephemeral range when\nomitted — with N runtimes the operator should not have to\nhand out port numbers.\n',
        ge=1,
        le=65535,
    )
    autoStart: bool | None = Field(
        True,
        description='Whether the watchdog spawns this runtime at startup and\nrespawns it on exit. False leaves it declared but\n`stopped`, which is how a rarely-used large model stays\nconfigured without holding VRAM.\n',
    )
    flags: dict[str, Any] | None = Field(
        None,
        description='Curated engine flags, keyed by the field names in the\nadapter\'s `flagSchema`. Validated on write: an unknown key\nis a 400, never a silent drop.\n\nThis is the per-model settings surface — the reason\n"tweaking llama.cpp settings for every different model" is a\ncomplaint we answer. Values here are engine *launch* flags;\nsampling parameters that ride on each request are the\ngateway\'s, not these.\n',
    )
    extraArgs: list[str] | None = Field(
        None,
        description='Verbatim extra arguments, appended after everything the\nadapter generated. The escape hatch for the long tail of\nflags a curated surface will always miss.\n\nUnvalidated by definition, so the UI must present it as the\nadvanced option it is: a bad value here surfaces as an\nengine that refuses to start, and the resolved `argv` plus\nthe captured engine output are how it gets diagnosed.\n',
    )
    env: dict[str, str] | None = Field(
        None,
        description='Extra environment variables for the engine process. Needed\nmore often than for a component — accelerator selection\n(`CUDA_VISIBLE_DEVICES`, `HIP_VISIBLE_DEVICES`) is how a\nruntime is pinned to one GPU, which is what makes two\nreplicas on two cards possible.\n',
    )
    workingDirectory: str | None = Field(
        None,
        description="Working directory for the engine process. Defaults to the\nbinary's own directory, which is what prebuilt llama.cpp\nreleases need to find their bundled shared libraries.\n",
    )
    binary: str | None = Field(
        None,
        description='Override the binary for this one runtime, ignoring whatever\nthe adapter discovered. For running one model on a custom\nbuild without disturbing the rest of the install.\n',
    )


class RuntimeStatus(StrEnum):
    """
    Operational state of an engine process. Distinct from
    `ComponentStatus`: an engine has no safe mode (nothing to
    recover a config from), and it has a model-load phase that a
    component does not.

    * `starting` — spawned, not yet answering its readiness probe
      at all.
    * `loading` — answering, but reporting the model is still being
      read into memory. Worth its own state rather than folding
      into `starting`: a large quant off a spinning disk can sit
      here for minutes, and an operator staring at a dashboard
      needs to know the difference between "working on it" and
      "wedged". This is exactly what a per-engine readiness probe
      buys — llama-server distinguishes the two on `/health` and a
      generic TCP check could not.
    * `ready` — model loaded and serving. The only state in which
      the gateway will route to it.
    * `stopped` — deliberately stopped, or declared with
      `autoStart: false`. Not an error; the respawn loop is
      suppressed.
    * `exited` — exited cleanly and is being respawned (transient).
    * `crashed` — exited non-zero repeatedly and the watchdog has
      given up. `lastError` and the captured engine output say why;
      `POST .../restart` retries.

    """

    starting = 'starting'
    loading = 'loading'
    ready = 'ready'
    stopped = 'stopped'
    exited = 'exited'
    crashed = 'crashed'


class RuntimeCapabilities(BaseModel):
    """
    What the running engine reports about itself, read back after it
    becomes ready rather than inferred from the declaration. The
    gateway keys routing decisions off these; the UI displays them.

    """

    contextLength: int | None = Field(
        None,
        description='Effective context window of the loaded model, as the engine\nresolved it — which is not necessarily what was asked for.\nA requested context larger than the model or the available\nmemory gets clamped by the engine, and the clamped value is\nthe true one.\n',
        ge=0,
    )
    parallelSlots: int | None = Field(
        None,
        description='Concurrent requests this runtime can serve. The unit of\ncapacity the gateway divides work across, so a single\nruntime with several slots and several runtimes with one\neach are the same kind of thing to the layer above.\n',
        ge=1,
    )
    embeddings: bool | None = Field(
        None, description='Whether this runtime was started in embedding mode.'
    )
    multimodal: bool | None = Field(
        None, description='Whether a projector was loaded alongside the model.'
    )


class Component(BaseModel):
    """
    Combined declarative + operational view of one supervised
    component. The declarative half (`name`, `kind`, `url`,
    `spawn`, `safeMode`) is what's persisted to `watchdog.yaml`.
    The operational half (`status`, `lastRestart`, `lastError`,
    `pid`) is observed at runtime and not persisted.

    """

    name: str = Field(
        ...,
        description="Operator-supplied label, also used in the gateway's `drivers` list.",
    )
    kind: ComponentKind
    url: AnyUrl = Field(
        ...,
        description='Canonical address. For spawned components the watchdog\nparses the port out of this URL and passes it via env var\n(`EUGENE_PLEXUS_<KIND>_BIND_PORT`); for remote components\nthis is what the watchdog probes.\n',
    )
    spawn: SpawnConfig | None = Field(
        None,
        description="Present iff this component runs locally under watchdog\nsupervision. Absence means it's remote (the watchdog only\nmonitors reachability).\n",
    )
    safeMode: bool | None = Field(
        False,
        description='When true the watchdog launches the spawned component with\n`EUGENE_PLEXUS_<KIND>_SAFE_MODE=1`, telling it to ignore its\nown config file and boot from defaults. Used to recover\nfrom a config that breaks startup. Ignored for remote\ncomponents.\n',
    )
    status: ComponentStatus
    pid: int | None = Field(
        None,
        description='Operating-system process id. Set only for spawned, currently-running components.',
    )
    lastRestart: AwareDatetime | None = Field(
        None, description='When the watchdog last started or restarted this component.'
    )
    lastError: str | None = Field(
        None,
        description="Most recent error observed for this component. Reset to null\non successful restart. Useful for surfacing why a component\nkeeps crashing in the UI's Components tab.\n",
    )


class ConfigField(BaseModel):
    """
    UI-renderable description of a single editable config field.

    """

    key: str = Field(
        ...,
        description='Stable machine-readable id, dot-separated for grouping\n(e.g. `"adapter.modelId"`).\n',
    )
    label: str = Field(..., description='Human-readable label for the UI.')
    description: str | None = Field(
        None, description='One-sentence explanation suitable for non-programmers.'
    )
    category: str = Field(
        ...,
        description='Group key for UI tabbing or sectioning (e.g. `"adapter"`,\n`"logging"`, `"network"`). Mapped to a display label via\n`ConfigSchema.categories`.\n',
    )
    valueType: ConfigValueType
    default: Any | None = Field(
        None,
        description='Default value if unset. Type matches `valueType`. Omitted\nfor fields with no default.\n',
    )
    enumValues: list[str] | None = Field(
        None, description='Allowed values when `valueType == enum`.'
    )
    suggestions: list[str] | None = Field(
        None,
        description="Discovery-time hints — values the operator might want\nbut which AREN'T enforced by validation. UIs render\nstring-typed fields with non-empty `suggestions` as a\ncombobox (free-text input with a dropdown of suggestions)\nrather than a strict dropdown. Use when the set of\nvalid values is large, partially-discoverable, or\nextends beyond what the component knows at the moment\n(e.g. local LLM model lists that update when the operator\npulls a new model). Distinct from `enumValues`:\nsuggestions are advisory, enumValues are mandatory.\n",
    )
    componentKindHint: ComponentKind | None = Field(
        None,
        description="Declarative rendering hint: this field references a peer\ncomponent of the given kind. UIs render any kind-hinted\nfield as a dropdown sourced from the watchdog's\n`/v1/components` (filtered by kind), with `(off)` as the\nfirst option (saves an empty string). For single-instance\nkinds (memory, identity, etc.) the dropdown UX collapses\nto effectively a toggle; for multi-instance kinds\n(inference-driver) the operator picks one. Pairs with a\nstring/url `valueType` — the saved value is still the\npeer's URL, the hint only changes how the UI looks it up.\nAvoids the OpenClaw trap of duplicating topology into\nfree-text URL fields the operator has to type by hand.\n",
    )
    enumLabels: list[str] | None = Field(
        None,
        description='Optional human-readable display labels paired one-to-one\nwith `enumValues`. UIs that render an enum as a dropdown\nshould show `enumLabels[i]` while still submitting\n`enumValues[i]` as the saved value. When omitted (or\nshorter than `enumValues`), UIs fall back to the raw\nvalue as the label. Useful where the stored key is\nmachine-friendly but the user-facing label isn\'t —\ne.g. `claude_subscription` saved, "Claude (Pro/Max)"\nshown.\n',
    )
    sensitive: bool | None = Field(
        False,
        description='If true, the value is redacted (`"<redacted>"`) in\n`ConfigDocument` responses but is accepted in\n`ConfigUpdateRequest`. Use for API keys, passwords, etc.\n',
    )
    required: bool | None = Field(
        False,
        description='If true, the component will refuse to start without this\nfield set (either in config or via env var fallback).\n',
    )
    minimum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    maximum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    pattern: str | None = Field(
        None, description='Regex validation hint for `string` / `url` / `file_path`.'
    )
    requiresRestart: bool | None = Field(
        False,
        description='If true, changes to this field via PATCH are accepted and\nstored but do not take effect until the component process\nrestarts. The UI should warn before submitting.\n',
    )
    showWhen: ConfigFieldShowWhen | None = Field(
        None,
        description="Conditional-rendering hint. When set, the UI should only\nrender this field when another field's current value matches\nthe condition. Used to hide adapter-specific fields\n(e.g. `openaiApiKey`) when a different adapter is selected.\nThe component still validates and stores the field\nregardless of UI visibility.\n",
    )


class ConfigSchema(BaseModel):
    """
    UI-renderable description of every editable config field this
    component accepts. Returned by `GET /v1/config/schema`. UIs use
    this to render a generic config editor without component-specific
    code.

    """

    component: str = Field(
        ..., description='Component identifier (e.g. `"inference-driver"`).'
    )
    fields: list[ConfigField]
    categories: dict[str, str] | None = Field(
        None,
        description='Map from category key (used in `ConfigField.category`) to\na human-readable section label. Optional; UIs may fall back\nto the raw key.\n',
    )


class ComponentEntry(BaseModel):
    """
    Declarative half of a Component, used for create / update
    request bodies. Status fields are server-owned and excluded.

    """

    name: str
    kind: ComponentKind
    url: AnyUrl
    spawn: SpawnConfig | None = None
    safeMode: bool | None = False


class EngineAcquisition(BaseModel):
    """
    Whether this host can be given a build of this engine, and which
    one. Answers the question before the operator commits to a
    several-hundred-megabyte download.

    """

    installable: bool = Field(
        ...,
        description='False means no published asset fits this host and `reason`\nsays why. This is a real outcome, not an error: upstream\npublishes no CUDA build for Linux, so a Linux box with an\nNVIDIA GPU cannot be served automatically and is told so\nrather than quietly handed a slower Vulkan build it never\nasked for.\n',
    )
    variant: str | None = Field(
        None, description='The asset variant that would be fetched, when installable.'
    )
    reason: str | None = Field(
        None,
        description='Why not, when `installable: false`. Written for the operator,\nnaming the way forward - build from source, use a container,\nor point `binary` at an existing build.\n',
    )
    detected: HostAccelerator | None = None
    latestVersion: str | None = Field(
        None, description='Newest upstream build we know of.'
    )
    latestPublishedAt: AwareDatetime | None = Field(
        None,
        description='When that build shipped. Deliberately the age of the newest\nbuild rather than a count of builds behind: llama.cpp\npublishes several a day, so "1,021 builds behind" is noise\nand "your build is three weeks old" is information.\n',
    )
    checkedAt: AwareDatetime | None = Field(
        None,
        description='When we last asked upstream. Checked at most daily and never\non the request path; a failed check leaves this stale rather\nthan raising anything.\n',
    )


class EngineDescriptor(BaseModel):
    """
    One engine adapter, plus what the watchdog found on this host.

    """

    engine: EngineKind
    available: bool = Field(
        ...,
        description='True iff a usable binary was found and successfully\nversion-probed. When false, `error` says why and runtimes\nfor this engine will fail to spawn.\n',
    )
    binaryPath: str | None = Field(
        None, description='Absolute path to the binary the adapter would spawn.'
    )
    version: str | None = Field(
        None,
        description='Version string as reported by the binary itself (for\nllama.cpp, the build number). Surfaced so an operator can\ntell what they are actually running, and so a flag that\nstopped working after an upgrade is diagnosable.\n',
    )
    origin: Origin | None = Field(
        None,
        description='Where the binary came from.\n\n* `managed` — fetched and verified by us. The one-click\n  path; not implemented until engine acquisition lands.\n* `configured` — an explicit path the operator set, because\n  they build llama.cpp themselves or want a specific build.\n* `path` — found on `PATH`.\n',
    )
    flagSchema: ConfigSchema | None = Field(
        None,
        description='The **curated** flag surface for this engine, as a standard\n`ConfigSchema` so the generic config editor renders it with\nno engine-specific UI code.\n\nCurated, not complete: `llama-server` has hundreds of flags\nand exposing them wholesale would produce a form nobody can\nuse. What is here is what a person actually turns —\ncontext size, GPU layers, batch size, parallel slots, flash\nattention. Anything omitted is still reachable through\n`RuntimeSpec.extraArgs`.\n',
    )
    error: str | None = Field(None, description='Populated when `available: false`.')
    managed: ManagedEngine | None = None
    acquisition: EngineAcquisition | None = None


class Runtime(BaseModel):
    """
    Combined declarative + operational view of one engine process.
    The declarative half is `RuntimeSpec` and is persisted; the
    operational half is observed and is not.

    """

    name: str
    engine: EngineKind
    modelPath: str
    modelAlias: str | None = Field(
        None,
        description='Resolved alias — the declared value, or the derived filename.',
    )
    host: str | None = None
    port: int | None = Field(
        None, description='Resolved port, including one assigned by the watchdog.'
    )
    autoStart: bool | None = None
    flags: dict[str, Any] | None = None
    extraArgs: list[str] | None = None
    env: dict[str, str] | None = None
    workingDirectory: str | None = None
    binary: str | None = None
    status: RuntimeStatus
    url: AnyUrl | None = Field(
        None,
        description="Where this engine is actually listening\n(`http://<host>:<port>`). This is the value an\ninference-driver's `baseUrl` points at, and the reason a\ndriver never needs to know about ports or argv.\n",
    )
    argv: list[str] | None = Field(
        None,
        description='The exact command line the watchdog spawned, as the adapter\nresolved it. Read-only and reported deliberately: the first\nquestion anyone debugging a local engine asks is "what\ncommand did you actually run", and every tool that hides the\nanswer makes that debugging worse. Copy-pasteable.\n',
    )
    pid: int | None = Field(
        None, description='OS process id. Set only while the engine is alive.'
    )
    engineVersion: str | None = Field(
        None, description='Version reported by the binary that is actually running.'
    )
    capabilities: RuntimeCapabilities | None = None
    lastRestart: AwareDatetime | None = None
    lastError: str | None = Field(
        None,
        description='Most recent failure for this runtime — a spawn error, a\nnon-zero exit, or a readiness probe that never passed.\nCleared on a successful start.\n',
    )


class ComponentList(BaseModel):
    components: list[Component] = Field(
        ...,
        description='Components in the order they were configured. The first-run\nwizard fills this in; later editing happens via the\nComponents tab.\n',
    )


class EngineList(BaseModel):
    engines: list[EngineDescriptor]


class RuntimeList(BaseModel):
    runtimes: list[Runtime]
